---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: version
  - name: tools
  - name: repo
outputs:
  - name: updated-version
caches:
  - path: gradle
  - path: maven
run:
  path: tools/tasks/get-version/task.sh
params:
  GIT_EMAIL:
  GIT_NAME:
