---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: tools
  - name: repo
  - name: version
outputs:
  - name: out
caches:
  - path: .gradle/
  - path: .m2/
run:
  path: /bin/bash
  args:
    - tools/tasks/prod-complete/task.sh
