---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: tools
  - name: version
  - name: repo-release
  - name: repo-master
  - name: m2

outputs:
  - name: out

run:
  path: repo-master/ci/tasks/bump-to-next-develop-version/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
