---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk
inputs:
  - name: tools
  - name: version
  - name: repo-release
  - name: repo-master
outputs:
  - name: out
caches:
  - path: gradle
  - path: maven
run:
  path: tools/tasks/bump-to-next-develop-version/task.sh
params:
  GIT_EMAIL:
  GIT_NAME:
