---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git

inputs:
  - name: tools
  - name: from-repo
  - name: to-repo

outputs:
  - name: out

run:
  path: tools/tasks/merge-branch/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
  SOURCE_BRANCH_NAME:
