---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base

inputs:
  - name: version
  - name: tools

outputs:
  - name: updated-version

run:
  path: tools/tasks/generate-version/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
