---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: version
  - name: apptx
outputs:
  - name: updated-version
run:
  path: apptx/tasks/generate-version/task.sh
params:
  GIT_EMAIL:
  GIT_NAME:
