---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: apptx
  - name: tools
  - name: repo
  - name: version
outputs:
  - name: out
caches:
  - path: gradle
  - path: maven
run:
  path: /bin/bash
  args:
    - apptx/tasks/build-and-upload/task.sh
