---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base

inputs:
  - name: tools
  - name: repo

outputs:
  - name: out

run:
  path: tools/tasks/create-branch/task.sh

params:
  GIT_EMAIL:
  GIT_NAME:
  BRANCH_NAME:
